name: Daily ETL

# Run the workflow on a schedule
on:
  schedule:
    - cron: '0 2 * * *' # Every day at 2 AM UTC
  workflow_dispatch: # Allows manual trigger from GitHub

jobs:
  run-etl:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repo
      - name: Checkout repo
        uses: actions/checkout@v3

      # Step 2: Set up Python 
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # Step 3: Install dependencies if needed
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run ETL shell script
      - name: Run ETL
        run: |
          chmod +x ./run_etl.sh
          ./run_etl.sh
